MouseParkApi/Controllers/AreaCreateController.cs
using MousePark.Models;
using MousePark.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MouseParkApi.Controllers
{
    public class AreaCreateController : Controller
    {
        // GET: ParkView
        private AreaService GetAreaService()
        {
            var service = new AreaService();
            return service;
        }
        public ActionResult Index()
        {
            var service = GetAreaService();
            return View(service.GetAreas());
        }
        public ActionResult Details(int id)
        {
            var svc = GetAreaService();
            var model = svc.GetAreaById(id);

            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(AreaCreate ca)
        {
            AreaController ac = new AreaController();
            ac.Post(ca);
            return View();
        }
        public ActionResult Delete(int id)
        {
            var svc = GetAreaService();
            var model = svc.GetAreaById(id);

            return View(model);
        }
    }
}

MouseParkApi/Controllers/ParkViewController.cs
using MousePark.Data;
using MousePark.Models;
using MousePark.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MouseParkApi.Controllers
{
    public class ParkViewController : Controller
    {
        // GET: ParkView
        private ParkService GetParkService()
        {
            var service = new ParkService();
            return service;
        }
        public ActionResult Index()
        {
            var service = GetParkService();
            return View(service.GetParks());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ParkCreate cp)
        {
            ParkController pc = new ParkController();
            pc.Post(cp);
            return View();
        }

    }
}

MouseParkApi/Controllers/RideCreateController.cs
using Microsoft.AspNet.Identity;
using MousePark.Data;
using MousePark.Models;
using MousePark.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MouseParkApi.Controllers
{
    public class RideCreateController : Controller
    {
        // GET: ParkView
        //public ActionResult Index()
        //{
        //    //IEnumerable<Ride> rides = null;

        //    //using (var client = new HttpClient())
        //    //{
        //    //    client.BaseAddress = new Uri("https://localhost:44391/api/");
        //    //    var responseTask = client.GetAsync("ride");
        //    //    responseTask.Wait();

        //    //    var result = responseTask.Result;
        //    //    if (result.IsSuccessStatusCode)
        //    //    {
        //    //        var readTask = result.Content.ReadAsAsync<IList<Ride>>();
        //    //        readTask.Wait();

        //    //        rides = readTask.Result;
        //    //    }
        //    //    else
        //    //    {
        //    //        rides = Enumerable.Empty<Ride>();

        //    //        ModelState.AddModelError(string.Empty, "Server Error.");
        //    //    }
        //    //}
        //    return View(/*rides*/);
        //}
        private RideService GetRideService()
        {
            var service = new RideService();
            return service;
        }
        public ActionResult Index()
        {
            var service = GetRideService();
            return View(service.GetRides());
        }
        public ActionResult Details(int id)
        {
            var svc = GetRideService();
            var model = svc.GetRideByID(id);

            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(RideCreate cr)
        {
            RideController rc = new RideController();
            rc.Post(cr);
            return View();
        }
        //[HttpPut]
        //public ActionResult Edit(RideEdit pr)
        //{
        //    RideController rp = new RideController();
        //    rp.Put(pr);
        //    return View();
        //}
        public ActionResult Edit(int id)
        {
            var service = GetRideService();
            var detail = service.GetRideByID(id);
            var model =
            new RideEdit
            {
                Name = detail.Name,
                RideDescription = detail.RideDescription,
                HeightReq = detail.HeightReq,
                RideType = detail.RideType
            };
            return View(model);
        }
        public ActionResult Delete(int id)
        {
            var svc = GetRideService();
            var model = svc.GetRideByID(id);

            return View(model);
        }
    }
}

MouseParkApi/Controllers/ShowCreateController.cs
using MousePark.Models;
using MousePark.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MouseParkApi.Controllers
{
    public class ShowCreateController : Controller
    {
        // GET: ParkView
        private ShowService GetShowService()
        {
            var service = new ShowService();
            return service;
        }
        public ActionResult Index()
        {
            var service = GetShowService();
            return View(service.GetShows());
        }
        public ActionResult Details(int id)
        {
            var svc = GetShowService();
            var model = svc.GetShowById(id);

            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ShowCreate cs)
        {
            ShowController sc = new ShowController();
            sc.Post(cs);
            return View();
        }
        public ActionResult Edit(int id)
        {
            var service = GetShowService();
            var detail = service.GetShowById(id);
            var model =
            new ShowEdit
            {
                Name = detail.Name,
                TargetAge = detail.TargetAge,
                Capacity = detail.Capacity,
                RunTime = detail.RunTime,
            };
            return View(model);
        }
        public ActionResult Delete(int id)
        {
            var svc = GetShowService();
            var model = svc.GetShowById(id);

            return View(model);
        }
    }
}

MouseParkApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mouse Park Land", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("View Parks", "Index", "ParkView", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("View Areas", "Index", "AreaCreate", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("View Rides", "Index", "RideCreate", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("View Eateries", "Index", "EateryCreate", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("View Shows", "Index", "ShowCreate", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Create Rating", "Create", "RatingCreate", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>